// Generated by CoffeeScript 1.6.2
/* 
==========================================================
 apiConsumer.js v1.0.0
https://github.com/manuelrojas
 ==========================================================
 Author:Manuel Rojas
 Date:4/9/2013
==========================================================
*/


(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  (function(window, $, EMPTY) {
    var ApiConsumer;

    ApiConsumer = (function() {
      function ApiConsumer() {
        this.logIn = __bind(this.logIn, this);
      }

      ApiConsumer.prototype.init = function() {
        ApiConsumer.holder = $('.profile');
        ApiConsumer.loginControl = $('.login-control');
        return $('button.btn#login').click(this.logIn);
      };

      ApiConsumer.prototype.logIn = function() {
        var account, pass, user;

        user = $('#inputEmail').val();
        pass = $('#inputPassword').val();
        account = {
          user: user,
          password: pass
        };
        $.ajax({
          url: '../api/login',
          type: "Post",
          dataType: "json",
          data: account,
          error: function(xhr, status, error) {
            return console.error(error);
          },
          success: function(account) {
            var $alertError, $alertSuccess, isValid;

            isValid = account.result;
            $alertSuccess = $('.alert.alert-success');
            $alertError = $('.alert.alert-error');
            $alertSuccess.addClass('hide');
            $alertError.addClass('hide');
            if (isValid) {
              $alertSuccess.removeClass('hide').addClass('in');
              /* Ajax call and build profile
              */

              return ApiConsumer.handleProfile(account.token);
            } else {
              return $alertError.removeClass('hide').addClass('in');
            }
          }
        });
        return false;
      };

      ApiConsumer.handleProfile = function(token) {
        return $.ajax({
          url: "../api/profile/" + token,
          type: "GET",
          dataType: "json",
          error: function(xhr, status, error) {
            return console.error(error);
          },
          success: function(profile) {
            return ApiConsumer.buildProfile(profile);
          }
        });
      };

      ApiConsumer.buildProfile = function(profile) {
        var profileMarkUp;

        console.log(profile);
        /* Profile Template
        */

        profileMarkUp = "<div class=\"span3\">\n  <strong>Name</strong> " + profile.Name + " <br>\n  <strong>Last Name</strong> " + profile.LastName + " <br>\n   <strong>Email</strong> " + profile.Email + " <br>\n  <strong>Phone</strong> " + profile.Phone + " <br>\n  <address>\n  <strong>" + profile.Address + "</strong><br>\n  795 Folsom Ave, Suite 600<br>\n  San Francisco, CA 94107<br>\n  <abbr title=\"Phone\">P:</abbr> (123) 456-7890\n  </address>\n</div>";
        ApiConsumer.holder.addClass('in');
        ApiConsumer.holder.append(profileMarkUp);
        return ApiConsumer.loginControl.addClass('hide');
      };

      return ApiConsumer;

    })();
    /* Create Api Consumer
    */

    return $(document).ready(function() {
      var apiConsumer;

      apiConsumer = new ApiConsumer();
      return apiConsumer.init();
    });
  })(window, jQuery);

}).call(this);
